name: Weekly Appium Test

on:
  schedule:
    - cron: '0 3 * * 1' # Setiap hari Senin jam 10:00 WIB (UTC+7)
  workflow_dispatch: # Bisa juga dijalankan manual dari GitHub UI

jobs:
  run-appium-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --base-path /wd/hub --log appium.log &
        shell: bash

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          emulator-options: -no-window -no-audio -no-boot-anim
          disable-animations: true
          script: echo "Emulator started"

      - name: Wait for Emulator Boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run WDIO Test (CI Config)
        run: npx wdio run wdio.github.conf.js

      - name: Upload Appium Log (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: appium-log
          path: appium.log
