name: Weekly Mobile Test

on:
  schedule:
    - cron: '0 4 * * 1' # Setiap Senin pukul 11:00 WIB
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  android-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Android Emulator and Execute Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_4
          disable-animations: false # Hindari error ADB
          script: |
            adb wait-for-device
            adb devices
            chmod +x ../../script/wait-for-emulator.sh
            npm run test:android
